### ISSUE TITLE
Rails.assets.precompile?

### ISSUE THREAD

**Issue by lifeiscontent** [middleman/middleman-sprockets#121]
I'm having issues using the `activate :asset_hash` feature.

``` scss
@font-face {
  font-family: "GothamHTF";
  font-style: normal;
  font-weight: 300;
  src: font-url("GothamHTF/GothamHTF-Light.eot?#iefix") format("embedded-opentype"),
       font-url("GothamHTF/GothamHTF-Light.woff2") format("woff2"),
       font-url("GothamHTF/GothamHTF-Light.woff") format("woff"),
       font-url("GothamHTF/GothamHTF-Light.ttf") format("truetype"),
       font-url("GothamHTF/GothamHTF-Light.svg#GothamHTF") format("svg");
}
```

is compiling to this

``` css
@font-face {
  font-family: "GothamHTF";
  font-style: normal;
  font-weight: 300;
  src: url(../fonts/GothamHTF/GothamHTF-Light-8a016ce1.eot?#iefix) format("embedded-opentype"),
       url(../fonts/GothamHTF/GothamHTF-Light-0b2e1266.woff2) format("woff2"),
       url(../fonts/GothamHTF/GothamHTF-Light-0b2e1266.woff) format("woff"),
       url(../fonts/GothamHTF/GothamHTF-Light-66359bda.ttf) format("truetype"),
       url(../fonts/GothamHTF/GothamHTF-Light-5623d59b.svg#GothamHTF) format("svg");
}
```

as you can see, the hash is the same for both the `woff` and `woff2` and it's not the same when the files are compiled.
