### ISSUE TITLE
image-url helper not working for nested pages

### ISSUE THREAD

**Issue by alem0lars** [middleman/middleman-sprockets#80]
If I use the SASS function `image-url` in a page which isn't directly root, I get a 404 error for the requested image.
This is because the generated path is relative and not absolute.

----

For example, with:

```SCSS
body {
  background-image: image-url("myimg.png"); // Or even with image-url("/myimg.png");
}
```

I'm getting:

```
GET http://localhost:4567/foo/bar/assets/images/myimg.png 404 (Not Found)
```

when I try to request that image from the page: `http://localhost:4567/foo/bar/baz.html`.

This is because `image-url` assumes the path relative to the current path, which is `/foo/bar`.

**Instead the generated URL should be `http://localhost:4567/assets/images/myimg.png` (without `foo/bar/`)**
