### ISSUE TITLE
font_url not working with asset_hash

### ISSUE THREAD

**Issue by nlsrchtr** [middleman/middleman-sprockets#84]
I would like to use a custom font and hashed assets. So I set up something like:

```css
@font-face {
  font-family: "my-custom-font";
  src: font_url("my-custom-font.eot");
  src: font_url("my-custom-font.eot?#iefix") format("embedded-opentype"),
    font_url("my-custom-font.woff") format("woff"),
    font_url("my-custom-font.ttf") format("truetype"),
    font_url("my-custom-font.svg#my-custom-font") format("svg");
  font-weight: normal;
  font-style: normal;
}
```

If I reload, the generated CSS only contains one hashed asset url, f.e.:

```css
@font-face {
  font-family: "my-custom-font";
  src: url("/fonts/my-custom-font-66bffac9.eot");
  src: url("my-custom-font-66bffac9.eot?#iefix") format("embedded-opentype"),
    url("/fonts/my-custom-font.woff") format("woff"),
    url("/fonts/my-custom-font.ttf") format("truetype"),
    url("/fonts/my-custom-font.svg#my-custom-font") format("svg");
  font-weight: normal;
  font-style: normal;
}
```

If I put some other font in the first place, it also gets the correct hash attached. Does anyone have an idea what is happening and how this can be improved? This is suboptimal since specially custom fonts will change and so the outdating of the cached file with the hash seems necessary for me.

Thanks for any hint!
